// The Solvay SPARK knowledge graph as a Neo4j schema.
// Generated by kg_neo4j_export.py from knowledge_graph.json.
//
// 354 nodes across 5 labels,
// 560 relationships across 11 types.

// --- node labels and their properties ---
// (:Process)  x202
//     code: string
//     description: string
//     in_bpml: boolean
//     jira_key: string

// (:Document)  x83
//     chars: integer
//     filename: string
//     format: string
//     source: string

// (:Spec)  x47
//     is_primary: boolean
//     ticket: string

// (:System)  x18
//     code: string
//     description: string

// (:Stream)  x4
//     code: string
//     description: string

// --- relationship types ---
// (:Process)-[:SUBPROCESS_OF]->(:Process)       x185
// (:Document)-[:INTERACTS_WITH]->(:System)      x70
// (:Document)-[:BELONGS_TO]->(:Stream)          x70
// (:Document)-[:SPECIFIES_PROCESS]->(:Process)  x70
// (:Document)-[:REFERENCES_TICKET]->(:Spec)     x41
// (:Document)-[:RUNS_ON]->(:System)             x40
// (:Document)-[:USES_UI]->(:System)             x28
// (:Document)-[:INTERFACES_WITH]->(:System)     x21
// (:Document)-[:IMPLEMENTS_TICKET]->(:Spec)     x13
// (:Document)-[:INTEGRATES_WITH]->(:System)     x12
// (:Document)-[:CONNECTS_TO]->(:System)         x10
