// The Solvay SPARK knowledge graph as a Neo4j schema.
// Generated by kg_neo4j_export.py from knowledge_graph.json.
//
// 11257 nodes across 6 labels,
// 20893 relationships across 8 types.

// --- node labels and their properties ---
// (:Chunk)  x8867
//     category: string
//     chunk_index: integer
//     chunk_key: string
//     heading_path: string
//     tokens: integer

// (:Process)  x1985
//     code: string
//     description: string
//     in_bpml: boolean
//     jira_key: string

// (:Document)  x218
//     bytes: integer
//     category: string
//     chars: integer
//     filename: string
//     format: string
//     source: string

// (:Spec)  x165
//     is_primary: boolean
//     ticket: string

// (:System)  x18
//     code: string
//     description: string
//     kind: string

// (:Stream)  x4
//     code: string
//     description: string

// --- relationship types ---
// (:Document)-[:HAS_CHUNK]->(:Chunk)            x8867
// (:Chunk)-[:MENTIONS]->(:System)               x3998
// (:Chunk)-[:MENTIONS]->(:Process)              x2695
// (:Document)-[:SPECIFIES_PROCESS]->(:Process)  x1947
// (:Process)-[:SUBPROCESS_OF]->(:Process)       x1846
// (:Document)-[:MENTIONS_SYSTEM]->(:System)     x556
// (:Chunk)-[:MENTIONS]->(:Stream)               x316
// (:Document)-[:BELONGS_TO]->(:Stream)          x237
// (:Chunk)-[:MENTIONS]->(:Spec)                 x228
// (:Document)-[:REFERENCES_TICKET]->(:Spec)     x190
// (:Document)-[:IMPLEMENTS_TICKET]->(:Spec)     x13
